version: "2"

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/

  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432

  puppetdb:
    container_name: puppetdb
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081

  puppetexplorer:
    container_name: puppetexplorer
    image: puppet/puppetexplorer
    ports:
      - 8080:80
    read_only: true
