# v1 file, for Jenkins compatibility
conjur:
  image: appliance-cuke-master
  environment:
    CONJUR_AUTHN_LOGIN: admin
    CONJUR_AUTHN_API_KEY: secret
    CONJUR_ACCOUNT: cucumber
  volumes:
    - .:/src
  ports:
    - 9443:443
  security_opt:
    - seccomp:unconfined
